name: GitHub Actions Linter and Optimizer

on: [push]

jobs:
  run-linter:
    name: GHA Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: ./  # Use local action
